### ISSUE TITLE
数据预处理木有'center'和‘joints_vis’

### ISSUE THREAD

**Issue by liuchanfeng165** [frankchen121212/MobilePose-master#2]
可否更新一下，谢谢

**Comment by frankchen121212** [comment]
> 可否更新一下，谢谢

我更新了一下数据，MPII 的train.json val.json已经上传，Penn Action的mean.npy也已上传

**Comment by liuchanfeng165** [comment]
> > 可否更新一下，谢谢
> 
> 我更新了一下数据，MPII 的train.json val.json已经上传，Penn Action的mean.npy也已上传

谢过，帮了大忙了

**Comment by liuchanfeng165** [comment]
> > 可否更新一下，谢谢
> 
> 我更新了一下数据，MPII 的train.json val.json已经上传，Penn Action的mean.npy也已上传

对了 frankchen哥们，你的训练集和验证集是怎么比例划分呢？我正在写数据预处理代码，原作有些问题，想确认。

**Comment by frankchen121212** [comment]
> > > 可否更新一下，谢谢
> > 
> > 
> > 我更新了一下数据，MPII 的train.json val.json已经上传，Penn Action的mean.npy也已上传
> 
> 对了 frankchen哥们，你的训练集和验证集是怎么比例划分呢？我正在写数据预处理代码，原作有些问题，想确认。

MPII 部分的 train.json 和 val.json 数据我使用了Simplebaseline for human pose estimation 部分的数据，github链接如下：
https://github.com/microsoft/human-pose-estimation.pytorch

json数据是原作 @leoxiaobin 他们组公开的
Onedrive链接如下：
https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110692&cid=56B9F9C97F261712

**Comment by liuchanfeng165** [comment]
> > > > 可否更新一下，谢谢
> > > 
> > > 
> > > 我更新了一下数据，MPII 的train.json val.json已经上传，Penn Action的mean.npy也已上传
> > 
> > 
> > 对了 frankchen哥们，你的训练集和验证集是怎么比例划分呢？我正在写数据预处理代码，原作有些问题，想确认。
> 
> MPII 部分的 train.json 和 val.json 数据我使用了Simplebaseline for human pose estimation 部分的数据，github链接如下：
> https://github.com/microsoft/human-pose-estimation.pytorch
> 
> json数据是原作 @leoxiaobin 他们组公开的
> Onedrive链接如下：
> https://onedrive.live.com/?authkey=%21AKqtqKs162Z5W7g&id=56B9F9C97F261712%2110692&cid=56B9F9C97F261712

/抱拳 有劳了~谢过

**Comment by liuchanfeng165** [comment]
@frankchen121212 小哥，你迭代几次得到介么好结果呢？我需要对比一下~
